import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Liquid} from 'liquid-gooey';
import '@fontsource/vazirmatn/400.css';
import '@fontsource/vazirmatn/500.css';
import '@fontsource/vazirmatn/600.css';
import '@fontsource/vazirmatn/700.css';
import './styles.css';

const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const now=()=>Date.now();
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const native=()=>window.AndroidApi;
const CODECRAFT_BASE='https://codecraftapi.com/v1';

function isNewerBuild(remoteCode,installedCode){const r=parseInt(remoteCode,10),i=parseInt(installedCode,10);return Number.isFinite(r)&&Number.isFinite(i)&&r>i}
const FALLBACK_MODEL='claude-opus-4.8';

const paths={
 menu:'M4 6h16M4 12h16M4 18h16', more:'M12 5.5v.01M12 12v.01M12 18.5v.01', plus:'M12 5v14M5 12h14', mic:'M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3ZM5 10v2a7 7 0 0 0 14 0v-2M12 19v3', send:'m5 12 7-7 7 7M12 5v14', edit:'M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z', search:'m21 21-4.35-4.35M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z', image:'M4 5h16v14H4zM8 13l3-3 5 5 2-2 2 2M9 9h.01', folder:'M3 6h6l2 2h10v11H3z', clock:'M12 3a9 9 0 1 0 9 9 9 9 0 0 0-9-9ZM12 7v5l3 2', puzzle:'M8 3h4a2 2 0 1 1 4 0h3v5a2 2 0 1 1 0 4v5h-5a2 2 0 1 1-4 0H5v-5a2 2 0 1 1 0-4V3h3Z', settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM4 12a8 8 0 0 1 .2-1.8l-2-1.5 2-3.4 2.4 1a8 8 0 0 1 3-1.7L10 2h4l.4 2.6a8 8 0 0 1 3 1.7l2.4-1 2 3.4-2 1.5A8 8 0 0 1 20 12c0 .6-.1 1.2-.2 1.8l2 1.5-2 3.4-2.4-1a8 8 0 0 1-3 1.7L14 22h-4l-.4-2.6a8 8 0 0 1-3-1.7l-2.4 1-2-3.4 2-1.5A8 8 0 0 1 4 12Z', back:'m15 18-6-6 6-6', copy:'M9 9h10v11H9zM5 4h10v3M5 4v12h2', share:'M18 8a3 3 0 1 0-2.8-4M6 14a3 3 0 1 0 0 6M18 14a3 3 0 1 0 0 6M8.6 15.4l6.8 3.2M8.6 8.6l6.8-3.2', trash:'M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14', pin:'M9 3h6l-1 5 4 4v2H6v-2l4-4-1-5ZM12 14v7', upload:'M12 16V4m0 0-4 4m4-4 4 4M4 20h16', archive:'M4 7h16v14H4zM3 3h18v4H3zM9 11h6', link:'M10 13a5 5 0 0 0 7.5.5l2-2a5 5 0 0 0-7-7l-1.1 1.1M14 11a5 5 0 0 0-7.5-.5l-2 2a5 5 0 0 0 7 7l1.1-1.1', volume:'M5 10v4h4l5 4V6l-5 4H5ZM17 9a4 4 0 0 1 0 6M19 6a8 8 0 0 1 0 12', refresh:'M20 6v6h-6M4 18v-6h6M6.5 8a7 7 0 0 1 11-2l2.5 3M17.5 16a7 7 0 0 1-11 2L4 15', x:'M6 6l12 12M18 6 6 18', check:'m5 12 4 4L19 6', chevron:'m9 18 6-6-6-6', camera:'M4 7h4l2-2h4l2 2h4v12H4zM12 10a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z', file:'M6 3h8l4 4v14H6zM14 3v5h5', globe:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18ZM3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18', info:'M12 10v7M12 7h.01M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18', key:'M15 8a5 5 0 1 1-4.6 7H3v-3h3V9h4.4A5 5 0 0 1 15 8Z', palette:'M12 3a9 9 0 0 0 0 18h2a2 2 0 0 0 0-4h-1a2 2 0 0 1 0-4h3a5 5 0 0 0 5-5c0-3-4-5-9-5ZM7 9h.01M9 6h.01M14 6h.01M17 9h.01', spark:'M12 2l1.7 5.3L19 9l-5.3 1.7L12 16l-1.7-5.3L5 9l5.3-1.7L12 2ZM19 15l.8 2.2L22 18l-2.2.8L19 21l-.8-2.2L16 18l2.2-.8L19 15Z', branch:'M6 3v8a4 4 0 0 0 4 4h8M14 11l4 4-4 4M6 3a2 2 0 1 0 0 .01', home:'M3 11l9-8 9 8v10h-6v-6H9v6H3z', rename:'M4 20h4l11-11-4-4L4 16v4ZM13 7l4 4', select:'M5 4h14v16H5zM9 9h6M9 13h6', eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Zm10-3a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z', moon:'M20 15a8 8 0 0 1-11-11 8 8 0 1 0 11 11Z', user:'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM4 21a8 8 0 0 1 16 0', shield:'M12 3l8 3v6c0 5-3.5 8-8 10-4.5-2-8-5-8-10V6l8-3Z', download:'M12 3v12m0 0 5-5m-5 5-5-5M4 21h16', play:'M8 5l11 7-11 7z', pause:'M8 5h3v14H8zM14 5h3v14h-3z', stop:'M7 7h10v10H7z', headphones:'M4 13v5h4v-7H4m16 2v5h-4v-7h4M4 13a8 8 0 0 1 16 0', sliders:'M4 6h10M18 6h2M4 12h2m4 0h10M4 18h8m4 0h4M14 4v4M8 10v4M14 16v4', logout:'M10 5H5v14h5M14 8l4 4-4 4M8 12h10'};
function Icon({name,size=21}){return <svg className="icon" style={{width:size,height:size}} viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]||paths.spark}/></svg>}
function IBtn({name,onClick,className='',label,size=21,disabled=false}){return <button disabled={disabled} aria-label={label||name} className={`icon-btn ${className}`} onClick={onClick}><Icon name={name} size={size}/></button>}

const defaultState=()=>({
 conversations:[{id:uid(),title:'گفتگوی جدید',messages:[],createdAt:now(),updatedAt:now(),pinned:false,archived:false,projectId:null}],
 activeId:null,
 projects:[],
 schedules:[],
 settings:{language:'fa',theme:'dark',accent:'white',provider:'CODECRAFT',baseUrl:CODECRAFT_BASE,apiNotes:'',selectedModel:FALLBACK_MODEL,models:[FALLBACK_MODEL],modelInfo:{},systemPrompt:'تو MindGPT هستی؛ یک دستیار دقیق، مفید و حرفه‌ای.',maxTokens:4096,voiceLanguage:'fa-IR',autoRead:false,sendOnEnter:false,compact:false},
 pluginWebSearch:true
});
function normalize(saved){const d=defaultState();if(!saved)return d;return {...d,...saved,settings:{...d.settings,...saved.settings,apiKey:''},conversations:(saved.conversations?.length?saved.conversations:d.conversations).map(c=>({...c,archived:!!c.archived,projectId:c.projectId||null}))}}
function useStore(){
 const [state,setState]=useState(()=>{try{return normalize(JSON.parse(localStorage.getItem('mindgpt.v4')||'null'))}catch{return defaultState()}});
 const [apiKey,setApiKey]=useState('');
 useEffect(()=>{if(!state.activeId&&state.conversations[0])setState(s=>({...s,activeId:s.conversations[0].id}))},[]);
 useEffect(()=>{const copy={...state,settings:{...state.settings,apiKey:undefined}};localStorage.setItem('mindgpt.v4',JSON.stringify(copy))},[state]);
 useEffect(()=>{try{const v=native()?.getSecret?.('apiKey')||native()?.getBundledApiKey?.()||sessionStorage.getItem('mindgpt.apiKey')||'';if(v)setApiKey(v)}catch{}},[]);
 const saveKey=v=>{setApiKey(v);try{native()?.setSecret?.('apiKey',v)}catch{sessionStorage.setItem('mindgpt.apiKey',v)}};
 return [state,setState,apiKey,saveKey];
}

function endpoint(){return CODECRAFT_BASE}
const pending=new Map();
window.__nativeResponse=(id,status,body)=>{const p=pending.get(id);if(p){pending.delete(id);p.resolve({status,body})}};
function request(method,url,headers={},body=''){if(!native())return fetch(url,{method,headers,body:body||undefined}).then(async r=>({status:r.status,body:await r.text()}));return new Promise((resolve,reject)=>{const id=uid();pending.set(id,{resolve,reject});native().request(id,method,url,JSON.stringify(headers),body||'');setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(new Error('Request timed out'))}},125000)})}
function apiError(status,body){let m='',code='';try{const j=JSON.parse(body);m=j?.error?.message||j?.message||'';code=j?.error?.code||j?.code||''}catch{}const detail=[code,m].filter(Boolean).join(' — ');if(status===0)return body||'خطای اتصال شبکه';if(status===401)return detail||'کلید API نامعتبر، حذف‌شده یا اشتباه است.';if(status===402)return detail||'اعتبار یا سهمیه حساب CodeCraft کافی نیست.';if(status===403)return detail||'کلید API scope لازم را ندارد.';if(status===404)return detail||'مدل یا endpoint پیدا نشد.';if(status===422)return detail||'درخواست توسط API معتبر شناخته نشد.';if(status===429)return detail||'محدودیت درخواست فعال شده است.';if(status===502)return detail||'ارائه‌دهنده مدل موقتاً خطا داده است.';if(status===503||status===529)return detail||'سرویس موقتاً در دسترس نیست.';return detail||`خطای سرویس (${status})`}
async function retryable(fn){let r;for(let i=0;i<3;i++){r=await fn();if(![429,503,529].includes(r.status))return r;if(i<2)await wait(i?2200:900)}return r}
async function loadModels(settings,key){if(!key)throw new Error('سرویس هوش مصنوعی در دسترس نیست.');const r=await request('GET',`${CODECRAFT_BASE}/models`,{Authorization:`Bearer ${key}`});if(r.status<200||r.status>=300)throw new Error(apiError(r.status,r.body));const j=JSON.parse(r.body);const raw=j?.data??j?.models??j?.items??j;const list=Array.isArray(raw)?raw:(raw&&typeof raw==='object'?Object.values(raw):[]);const info={};const models=list.filter(m=>m?.id&&m.type!=='embedding').map(m=>{info[m.id]=m;return m.id});return {provider:'CODECRAFT',models:[...new Set(models)],info}}
function contentParts(m,modelInfo){const text=[m.text||'',...(m.attachments||[]).filter(a=>a.textContent).map(a=>`[File: ${a.name}]\n${a.textContent}`)].filter(Boolean).join('\n\n');const images=(m.attachments||[]).filter(a=>a.data?.startsWith('data:image/'));if(!images.length)return text;const caps=modelInfo?.capabilities||[];if(!caps.includes('vision'))return text||'[Image attached — selected model does not advertise vision support]';return [{type:'text',text:text||'Analyze the attached image.'},...images.map(a=>({type:'image_url',image_url:{url:a.data}}))]}
async function sendApi(settings,key,messages,{webSearch=false,think=false}={}){if(!key)throw new Error('سرویس هوش مصنوعی در دسترس نیست.');let model=settings.selectedModel||FALLBACK_MODEL;let info=settings.modelInfo?.[model]||{};try{const live=await loadModels(settings,key);if(live.models.length){if(!live.models.includes(model))model=live.models[0];info=live.info?.[model]||info}}catch{}const caps=info?.capabilities||[];if(webSearch&&!caps.includes('web_search'))throw new Error('مدل انتخاب‌شده Web Search واقعی ندارد. یک مدل دارای قابلیت Web انتخاب کن.');if(think&&!caps.includes('reasoning'))throw new Error('مدل انتخاب‌شده Reasoning ندارد. یک مدل Reasoning انتخاب کن.');const system=[...(settings.systemPrompt?[{role:'system',content:settings.systemPrompt}]:[])];if(webSearch)system.push({role:'system',content:'Use your built-in web search for this request. Ground fresh claims in retrieved web information and include source links when available.'});const payload={model,messages:[...system,...messages.filter(m=>!m.error).map(m=>({role:m.role==='assistant'?'assistant':'user',content:contentParts(m,info)}))],max_tokens:Math.max(think?16000:8192,settings.maxTokens||8192),temperature:think?.7:1};const r=await retryable(()=>request('POST',`${CODECRAFT_BASE}/chat/completions`,{'Content-Type':'application/json','Accept':'application/json',Authorization:`Bearer ${key}`},JSON.stringify(payload)));if(r.status<200||r.status>=300)throw new Error(apiError(r.status,r.body));let data;try{data=JSON.parse(r.body)}catch{throw new Error('پاسخ سرویس قابل پردازش نیست.')}const msg=data.choices?.[0]?.message||{};const answer=typeof msg.content==='string'?msg.content:(Array.isArray(msg.content)?msg.content.map(x=>x?.text||x?.content||'').join('\n'):'');return {text:answer.trim()||'پاسخی دریافت نشد.',reasoning:(msg.reasoning_content||'').trim(),model:data.model||model,web:webSearch};}

function copyText(text,toast){try{native()?.copy?.(text);toast('کپی شد')}catch{navigator.clipboard?.writeText(text);toast('کپی شد')}}
function shareText(text){if(native()?.share)native().share(text);else navigator.share?.({text})}
function formatTime(t){try{return new Intl.DateTimeFormat('fa-IR',{hour:'2-digit',minute:'2-digit'}).format(new Date(t))}catch{return ''}}
async function readFile(file){const data=await new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>resolve(null);r.readAsDataURL(file)});const ext=file.name.split('.').pop()?.toLowerCase();const textLike=file.type.startsWith('text/')||['txt','md','json','csv','xml','html','css','js','jsx','ts','tsx','kt','java','py','sql','yaml','yml'].includes(ext);let textContent='';if(textLike&&file.size<2_000_000)textContent=await file.text().catch(()=> '');return {id:uid(),name:file.name,type:file.type||'application/octet-stream',size:file.size,data,textContent}}

function App(){
 const [state,setState,apiKey,setApiKey]=useStore();const [updateInfo,setUpdateInfo]=useState(null);const [screen,setScreen]=useState('chat');const [drawer,setDrawer]=useState(false);const [topMenu,setTopMenu]=useState(false);const [attach,setAttach]=useState(false);const [messageMenu,setMessageMenu]=useState(null);const [chatMenu,setChatMenu]=useState(null);const [plusOpen,setPlusOpen]=useState(false);const [toast,setToast]=useState('');const [find,setFind]=useState(false);const [findQ,setFindQ]=useState('');const [edit,setEdit]=useState(null);const [selectText,setSelectText]=useState(null);const [voice,setVoice]=useState(false);const [tts,setTts]=useState(null);const [imageView,setImageView]=useState(null);
 const active=state.conversations.find(c=>c.id===state.activeId)||state.conversations[0];const isFa=state.settings.language==='fa';
 const patchSettings=p=>setState(s=>({...s,settings:{...s.settings,...p}}));
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),1800)};
 useEffect(()=>{window.__mindgptToast=notify;return()=>delete window.__mindgptToast},[]);
 const patchChat=(id,fn)=>setState(s=>({...s,conversations:s.conversations.map(c=>c.id===id?fn(c):c)}));
 const selectChat=id=>{setState(s=>({...s,activeId:id}));setDrawer(false);setScreen('chat')};
 const newChat=()=>{const c={id:uid(),title:isFa?'گفتگوی جدید':'New chat',messages:[],createdAt:now(),updatedAt:now(),pinned:false,archived:false,projectId:null};setState(s=>({...s,conversations:[c,...s.conversations],activeId:c.id}));setDrawer(false);setScreen('chat')};
 const removeChat=id=>{setState(s=>{const left=s.conversations.filter(c=>c.id!==id);const list=left.length?left:[{id:uid(),title:'گفتگوی جدید',messages:[],createdAt:now(),updatedAt:now(),pinned:false,archived:false,projectId:null}];return {...s,conversations:list,activeId:s.activeId===id?list[0].id:s.activeId}});setChatMenu(null);setTopMenu(false)};
 useEffect(()=>{const vv=visualViewport;const update=()=>document.documentElement.style.setProperty('--vvh',`${vv?.height||innerHeight}px`);update();vv?.addEventListener('resize',update);vv?.addEventListener('scroll',update);return()=>{vv?.removeEventListener('resize',update);vv?.removeEventListener('scroll',update)}},[]);
 useEffect(()=>{document.documentElement.dataset.theme=state.settings.theme;document.documentElement.dataset.accent=state.settings.accent||'white';document.documentElement.dir=isFa?'rtl':'ltr';document.documentElement.lang=isFa?'fa':'en'},[isFa,state.settings.theme,state.settings.accent]);
 useEffect(()=>{window.__updateAvailable=(json)=>{try{setUpdateInfo(JSON.parse(json))}catch{}};setTimeout(()=>native()?.checkForUpdate?.(false),900);return()=>delete window.__updateAvailable},[]);
 useEffect(()=>{window.__handleBack=()=>{if(plusOpen){setPlusOpen(false);return true}if(imageView){setImageView(null);return true}if(voice){setVoice(false);native()?.stopSpeech?.();return true}if(edit){setEdit(null);return true}if(selectText){setSelectText(null);return true}if(drawer||topMenu||attach||messageMenu||chatMenu||find){setDrawer(false);setTopMenu(false);setAttach(false);setMessageMenu(null);setChatMenu(null);setFind(false);return true}if(screen!=='chat'){setScreen('chat');return true}return false};return()=>delete window.__handleBack},[plusOpen,imageView,voice,edit,selectText,drawer,topMenu,attach,messageMenu,chatMenu,find,screen]);
 const go=n=>{setScreen(n);setDrawer(false)};
 return <div className="app-root">
   {screen==='chat'&&<Chat state={state} setState={setState} active={active} apiKey={apiKey} patchChat={patchChat} isFa={isFa} openDrawer={()=>setDrawer(true)} newChat={newChat} topMenu={topMenu} setTopMenu={setTopMenu} attach={attach} setAttach={setAttach} messageMenu={messageMenu} setMessageMenu={setMessageMenu} notify={notify} find={find} setFind={setFind} findQ={findQ} setFindQ={setFindQ} setEdit={setEdit} setSelectText={setSelectText} setVoice={setVoice} setTts={setTts} setImageView={setImageView} removeChat={removeChat} openPlus={()=>setPlusOpen(true)}/>} 
   {screen==='settings'&&<Settings state={state} patchSettings={patchSettings} go={go} isFa={isFa}/>}
   {screen==='models'&&<ModelSettings settings={state.settings} patchSettings={patchSettings} apiKey={apiKey} go={go} isFa={isFa} notify={notify}/>} {screen==='appearance'&&<Appearance settings={state.settings} patchSettings={patchSettings} go={go} isFa={isFa}/>} 
   {screen==='personalization'&&<Personalization settings={state.settings} patchSettings={patchSettings} go={go} isFa={isFa}/>} 
   {screen==='voiceSettings'&&<VoiceSettings settings={state.settings} patchSettings={patchSettings} go={go} isFa={isFa}/>} 
   {screen==='data'&&<DataControls state={state} setState={setState} go={go} isFa={isFa} notify={notify}/>} 
   {['images','library','projects','scheduled','plugins'].includes(screen)&&<HubScreen kind={screen} state={state} setState={setState} go={go} isFa={isFa} selectChat={selectChat} setImageView={setImageView} notify={notify}/>} 
   {drawer&&<><div className="backdrop" onClick={()=>setDrawer(false)}/><Drawer state={state} active={active} selectChat={selectChat} newChat={newChat} go={go} isFa={isFa} setChatMenu={setChatMenu}/></>}
   {chatMenu&&<ChatContext chat={state.conversations.find(c=>c.id===chatMenu)} close={()=>setChatMenu(null)} patchChat={patchChat} removeChat={removeChat} state={state} setState={setState} notify={notify} isFa={isFa}/>} 
   {plusOpen&&<PlusPage close={()=>setPlusOpen(false)} isFa={isFa}/>} 
   {edit&&<EditMessage msg={edit.msg} close={()=>setEdit(null)} save={text=>{patchChat(active.id,c=>{const i=c.messages.findIndex(m=>m.id===edit.msg.id);return {...c,messages:[...c.messages.slice(0,i),{...edit.msg,text}],updatedAt:now()}});setEdit(null)}}/>}
   {selectText&&<SelectText msg={selectText} close={()=>setSelectText(null)}/>} 
   {voice&&<VoiceMode isFa={isFa} settings={state.settings} close={()=>setVoice(false)} onText={text=>{window.__mindgptVoiceText?.(text)}} notify={notify}/>} 
   {tts&&<TtsBar item={tts} close={()=>{native()?.stopSpeak?.();setTts(null)}} isFa={isFa}/>} 
   {imageView&&<ImageViewer item={imageView} close={()=>setImageView(null)} remove={()=>{patchChat(active.id,c=>({...c,messages:c.messages.map(m=>({...m,attachments:(m.attachments||[]).filter(a=>a.id!==imageView.id)}))}));setImageView(null)}}/>}
   {updateInfo&&<UpdatePrompt info={updateInfo} close={()=>setUpdateInfo(null)} isFa={isFa}/>}
   {toast&&<div className="toast">{toast}</div>}
 </div>
}

function Chat({state,setState,active,apiKey,patchChat,isFa,openDrawer,newChat,topMenu,setTopMenu,attach,setAttach,messageMenu,setMessageMenu,notify,find,setFind,findQ,setFindQ,setEdit,setSelectText,setVoice,setTts,setImageView,removeChat,openPlus}){
 const [draft,setDraft]=useState('');const [files,setFiles]=useState([]);const [thinking,setThinking]=useState(false);const cancelRef=useRef({cancelled:false});const swipeRef=useRef(null);const [webSearch,setWebSearch]=useState(false);const [thinkMode,setThinkMode]=useState(false);const [recording,setRecording]=useState(false);const [speechState,setSpeechState]=useState('idle');const [partial,setPartial]=useState('');const [level,setLevel]=useState(.05);const scrollRef=useRef();const photoRef=useRef();const fileRef=useRef();const cameraRef=useRef();
 useEffect(()=>{setTimeout(()=>scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:'smooth'}),40)},[active?.messages?.length,thinking]);
 useEffect(()=>{window.__mindgptVoiceText=t=>setDraft(d=>`${d}${d?' ':''}${t}`);window.__speechPartial=t=>setPartial(t);window.__speechLevel=v=>setLevel(v);window.__speechResult=t=>{setDraft(d=>`${d}${d?' ':''}${t}`);setPartial('')};window.__speechState=s=>{setSpeechState(s);if(s==='stopped')setRecording(false)};window.__speechError=()=>{setRecording(false);setPartial('');notify(isFa?'دسترسی یا سرویس تشخیص صدا در دسترس نیست':'Speech recognition is unavailable')};return()=>{delete window.__mindgptVoiceText}},[isFa]);
 if(!active)return null;
 const messages=active.messages||[];const q=findQ.trim().toLowerCase();
 async function pick(e){const chosen=[...e.target.files||[]];e.target.value='';const read=await Promise.all(chosen.slice(0,6).map(readFile));setFiles(f=>[...f,...read].slice(0,8));setAttach(false)}
 function toggleRecord(){if(recording){const t=partial.trim();native()?.stopSpeech?.();if(t)setDraft(d=>`${d}${d?' ':''}${t}`);setRecording(false);setPartial('');notify(isFa?'متن آماده شد':'Text ready')}else{setRecording(true);setPartial('');native()?.startSpeech?.(isFa?'fa-IR':'en-US')}}
 function cancelGeneration(){cancelRef.current.cancelled=true;setThinking(false);notify(isFa?'پاسخ متوقف شد':'Response stopped')}
 function swipeStart(e){const p=e.touches?.[0]||e;swipeRef.current={x:p.clientX,y:p.clientY}}
 function swipeEnd(e){if(!swipeRef.current)return;const p=e.changedTouches?.[0]||e,dx=p.clientX-swipeRef.current.x,dy=Math.abs(p.clientY-swipeRef.current.y);swipeRef.current=null;if(dx>70&&dy<70&&p.clientX<innerWidth)openDrawer()}
 async function send({forceWeb=webSearch,baseMessages=null}={}){const text=draft.trim();if((!text&&!files.length)||thinking)return;const token={cancelled:false};cancelRef.current=token;const user={id:uid(),role:'user',text,attachments:files,createdAt:now()};const history=baseMessages||[...messages,user];patchChat(active.id,c=>({...c,title:c.messages.length?c.title:(text.slice(0,42)||'گفتگوی جدید'),messages:history,updatedAt:now()}));setDraft('');setFiles([]);setThinking(true);setWebSearch(false);try{const result=await sendApi(state.settings,apiKey,history,{webSearch:forceWeb,think:thinkMode});if(token.cancelled)return;const ai={id:uid(),role:'assistant',text:result.text,reasoning:result.reasoning,model:result.model,attachments:[],createdAt:now(),web:result.web,thought:thinkMode};patchChat(active.id,c=>({...c,messages:[...c.messages,ai],updatedAt:now()}));if(state.settings.autoRead)native()?.speak?.(answer,isFa?'fa-IR':'en-US')}catch(e){if(!token.cancelled)patchChat(active.id,c=>({...c,messages:[...c.messages,{id:uid(),role:'assistant',text:'',error:e.message,createdAt:now()}]}))}finally{if(!token.cancelled)setThinking(false)}}
 async function retryMessage(msg,useWeb=false){if(thinking)return;const idx=messages.findIndex(m=>m.id===msg.id);const base=messages.slice(0,msg.role==='assistant'?idx:idx+1).filter(m=>!m.error);patchChat(active.id,c=>({...c,messages:base}));setThinking(true);setMessageMenu(null);try{const result=await sendApi(state.settings,apiKey,base,{webSearch:useWeb,think:false});patchChat(active.id,c=>({...c,messages:[...c.messages,{id:uid(),role:'assistant',text:result.text,reasoning:result.reasoning,model:result.model,attachments:[],createdAt:now(),web:result.web}],updatedAt:now()}))}catch(e){patchChat(active.id,c=>({...c,messages:[...c.messages,{id:uid(),role:'assistant',text:'',error:e.message,createdAt:now()}]}))}finally{setThinking(false)}}
 function branch(msg){const idx=messages.findIndex(m=>m.id===msg.id);const c={...active,id:uid(),title:`${active.title} · branch`,messages:messages.slice(0,idx+1).map(m=>({...m,id:uid()})),pinned:false,createdAt:now(),updatedAt:now()};setState(s=>({...s,conversations:[c,...s.conversations],activeId:c.id}));setMessageMenu(null)}
 function speak(msg){native()?.speak?.(msg.text,isFa?'fa-IR':'en-US');setTts({text:msg.text,title:active.title})}
 function shareChat(){shareText(messages.map(m=>`${m.role==='user'?'You':'MindGPT'}: ${m.text||m.error||''}`).join('\n\n'));setTopMenu(false)}
 function archive(){patchChat(active.id,c=>({...c,archived:true}));setTopMenu(false);newChat()}
 return <div className="screen chat-screen" onTouchStart={swipeStart} onTouchEnd={swipeEnd}>
   <header className="chat-topbar">
    <div className="top-left"><div className="glass-control single"><IBtn name="menu" onClick={openDrawer}/></div></div>
    <button className="get-plus-pill" onClick={openPlus} aria-label={isFa?'مشاهده MindGPT Plus':'View MindGPT Plus'}><span>Get Plus</span><b>✦</b></button>
    <div className="top-right"><div className="glass-control twin"><IBtn name="edit" onClick={newChat}/><span className="control-seam"/><IBtn name="more" className="top-more" onClick={()=>setTopMenu(v=>!v)}/></div></div>
   </header>
   {find&&<div className="findbar"><IBtn name="back" onClick={()=>{setFind(false);setFindQ('')}}/><div className="find-input"><Icon name="search" size={18}/><input autoFocus value={findQ} onChange={e=>setFindQ(e.target.value)} placeholder={isFa?'جستجو در گفتگو':'Search in chat'}/></div><span className="find-count">{q?messages.filter(m=>(m.text||'').toLowerCase().includes(q)).length:0}</span></div>}
   <main ref={scrollRef} className="messages">
    {!messages.length&&!thinking?<Empty isFa={isFa}/>:messages.map(m=><Message key={m.id} m={m} highlight={q} onMenu={()=>setMessageMenu(m)} onRetry={()=>retryMessage(m)} onSpeak={()=>speak(m)} onImage={setImageView} notify={notify}/>) }
    {thinking&&<div className="assistant-row"><div className="reference-thinking"><span className="think-spark">✦</span><div><b>{thinkMode?(isFa?'در حال فکر کردن':'Thinking'):(webSearch?(isFa?'در حال جستجوی وب':'Searching the web'):(isFa?'در حال پاسخ دادن':'Responding'))}</b><small>{isFa?'MindGPT':'MindGPT'}</small></div><i/><i/><i/></div></div>}
    <div className="bottom-spacer"/>
   </main>
   <div className="composer-wrap"><div className="composer-shell"><div className="mode-chips">{webSearch&&<button onClick={()=>setWebSearch(false)}><Icon name="search" size={14}/>{isFa?'وب واقعی':'Web'}</button>}{thinkMode&&<button onClick={()=>setThinkMode(false)}>✦ {isFa?'تفکر عمیق':'Reasoning'}</button>}</div>
    {!!files.length&&<div className="attachment-strip">{files.map(a=><div className="attach-chip" key={a.id}>{a.type.startsWith('image/')?<img src={a.data}/>:<Icon name="file"/>}<span>{a.name}</span><button onClick={()=>setFiles(x=>x.filter(z=>z.id!==a.id))}>×</button></div>)}</div>}
    {recording?<div className="recording-composer"><button className="record-x" onClick={()=>{native()?.stopSpeech?.();setRecording(false);setPartial('')}}><Icon name="x"/></button><Wave level={level}/><div className="partial">{partial||(speechState==='processing'?(isFa?'در حال تبدیل به متن…':'Converting to text…'):(isFa?'در حال گوش دادن…':'Listening…'))}</div><button className="record-stop" onClick={toggleRecord}><Icon name="stop" size={17}/></button><button className="record-done" onClick={()=>{const t=partial.trim();native()?.stopSpeech?.();if(t)setDraft(d=>`${d}${d?' ':''}${t}`);setRecording(false);setPartial('');notify(isFa?'تبدیل به متن انجام شد':'Converted to text')}}><Icon name="check" size={18}/></button></div>:<div className="composer">
      <Liquid blur={6} contrast={18} fill="var(--composer)"><Liquid.Item effect="morph" x={0} y={0} transition="bouncy"><button className="plus" onClick={()=>setAttach(v=>!v)}><Icon name="plus"/></button></Liquid.Item></Liquid>
      <textarea rows={1} value={draft} onInput={e=>{e.currentTarget.style.height='40px';e.currentTarget.style.height=Math.min(e.currentTarget.scrollHeight,144)+'px'}} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&state.settings.sendOnEnter&&!e.shiftKey){e.preventDefault();send()}}} placeholder={isFa?'پیام به MindGPT':'Message MindGPT'}/>
      <button className="mic" onClick={toggleRecord}><Icon name="mic" size={20}/></button>
      {thinking?<button className="send stop-generation" onClick={cancelGeneration}><Icon name="stop" size={16}/></button>:draft.trim()||files.length?<button className="send" onClick={()=>send()}><Icon name="send" size={19}/></button>:<button className="voice-launch" onClick={()=>setVoice(true)}><Icon name="headphones" size={18}/></button>}
    </div>}
   </div></div>
   <input ref={cameraRef} className="hidden-input" type="file" accept="image/*" capture="environment" onChange={pick}/><input ref={photoRef} className="hidden-input" type="file" accept="image/*" multiple onChange={pick}/><input ref={fileRef} className="hidden-input" type="file" multiple onChange={pick}/>
   {attach&&<><div className="sheet-back" onClick={()=>setAttach(false)}/><AttachmentSheet camera={()=>cameraRef.current?.click()} photos={()=>photoRef.current?.click()} files={()=>fileRef.current?.click()} plugin={()=>{setWebSearch(v=>!v);notify(!webSearch?(isFa?'جستجوی وب روشن شد':'Web search enabled'):(isFa?'جستجوی وب خاموش شد':'Web search disabled'))}} think={()=>{setThinkMode(v=>!v);notify(!thinkMode?(isFa?'Reasoning واقعی روشن شد':'Reasoning enabled'):(isFa?'Reasoning خاموش شد':'Reasoning disabled'))}} isFa={isFa} webSearch={webSearch}/></>}
   {topMenu&&<><div className="menu-dismiss" onClick={()=>setTopMenu(false)}/><div className="popup top-menu"><Menu icon="share" text={isFa?'اشتراک‌گذاری':'Share'} onClick={shareChat}/><Menu icon="pin" text={active.pinned?(isFa?'برداشتن سنجاق':'Unpin'):(isFa?'سنجاق کردن':'Pin')} onClick={()=>{patchChat(active.id,c=>({...c,pinned:!c.pinned}));setTopMenu(false)}}/><Menu icon="folder" text={isFa?'افزودن به پروژه':'Add to project'} onClick={()=>{const p=state.projects[0];if(p)patchChat(active.id,c=>({...c,projectId:p.id}));else notify(isFa?'اول از بخش Projects یک پروژه بساز':'Create a project first');setTopMenu(false)}}/><Menu icon="upload" text={isFa?'فایل‌های آپلودشده':'Uploaded files'} onClick={()=>{setTopMenu(false);fileRef.current?.click()}}/><Menu icon="search" text={isFa?'جستجو در گفتگو':'Find in chat'} onClick={()=>{setFind(true);setTopMenu(false)}}/><Menu icon="home" text={isFa?'افزودن به خانه':'Add to home'} onClick={()=>{notify(isFa?'این گفتگو در بالای فهرست سنجاق شد':'Chat pinned to the top');patchChat(active.id,c=>({...c,pinned:true}));setTopMenu(false)}}/><Menu icon="archive" text={isFa?'بایگانی':'Archive'} onClick={archive}/><Menu icon="trash" danger text={isFa?'حذف':'Delete'} onClick={()=>removeChat(active.id)}/></div></>}
   {messageMenu&&<MessageContext msg={messageMenu} close={()=>setMessageMenu(null)} copy={()=>{copyText(messageMenu.text,notify);setMessageMenu(null)}} select={()=>{setSelectText(messageMenu);setMessageMenu(null)}} edit={()=>{setEdit({msg:messageMenu});setMessageMenu(null)}} share={()=>{shareText(messageMenu.text);setMessageMenu(null)}} branch={()=>branch(messageMenu)} retry={()=>retryMessage(messageMenu,false)} web={()=>retryMessage(messageMenu,true)} isFa={isFa}/>} 
 </div>
}
function Empty({isFa}){return <div className="empty"><div className="empty-mark">✦</div><h1>{isFa?'چه کمکی از دستم برمیاد؟':'What can I help with?'}</h1><div className="suggestions"><span>✎ {isFa?'نوشتن و ویرایش':'Write & edit'}</span><span>◈ {isFa?'تحلیل فایل و تصویر':'Analyze files & images'}</span><span>⌕ {isFa?'پرسش و پاسخ':'Ask anything'}</span></div></div>}
function RichText({text,highlight}){
 if(!text)return null;
 const parts=text.split(/(```[\s\S]*?```)/g);
 return <div className="rich-text">{parts.map((part,i)=>{
  if(part.startsWith('```')){
   const m=part.match(/^```([^\n]*)\n?([\s\S]*?)```$/);const lang=(m?.[1]||'').trim();const code=m?.[2]??part.slice(3,-3);
   return <CodeBlock key={i} code={code} lang={lang}/>;
  }
  return <MarkdownChunk key={i} text={part} highlight={highlight}/>;
 })}</div>
}
function MarkdownChunk({text,highlight}){
 const lines=text.split('\n');
 return <>{lines.map((line,i)=>{
  const hm=line.match(/^(#{1,4})\s+(.+)$/);if(hm){const T=`h${Math.min(4,hm[1].length+1)}`;return <T key={i}>{inlineMd(hm[2],highlight)}</T>}
  if(/^\s*[-*]\s+/.test(line))return <div className="md-li" key={i}>• <span>{inlineMd(line.replace(/^\s*[-*]\s+/,''),highlight)}</span></div>;
  if(/^\s*\d+\.\s+/.test(line))return <div className="md-li" key={i}><span>{line.match(/^\s*(\d+)\./)?.[1]}.</span> <span>{inlineMd(line.replace(/^\s*\d+\.\s+/,''),highlight)}</span></div>;
  return line?<p key={i}>{inlineMd(line,highlight)}</p>:<div className="md-gap" key={i}/>;
 })}</>
}
function inlineMd(text,highlight){
 const bits=text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g);
 return bits.map((x,i)=>x.startsWith('**')&&x.endsWith('**')?<strong key={i}>{x.slice(2,-2)}</strong>:x.startsWith('`')&&x.endsWith('`')?<code className="inline-code" key={i}>{x.slice(1,-1)}</code>:<span key={i}>{highlight?mark(x,highlight):x}</span>)
}
function CodeBlock({code,lang}){const [ok,setOk]=useState(false);async function cp(){await copyText(code);setOk(true);setTimeout(()=>setOk(false),2000)}return <div className="code-card"><div className="code-head"><span>{lang||'code'}</span><button onClick={cp}>{ok?<><Icon name="check" size={15}/> کپی شد</>:<><Icon name="copy" size={15}/> کپی</>}</button></div><pre><code>{code}</code></pre></div>}

function mark(text,q){if(!q)return text;const parts=text.split(new RegExp(`(${q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'ig'));return parts.map((p,i)=>p.toLowerCase()===q.toLowerCase()?<mark key={i}>{p}</mark>:p)}
function Message({m,highlight,onMenu,onRetry,onSpeak,onImage,notify}){const timer=useRef();const [copied,setCopied]=useState(false);async function copyMsg(){await copyText(m.text,notify);setCopied(true);setTimeout(()=>setCopied(false),2000)}const start=()=>{timer.current=setTimeout(onMenu,480)};const cancel=()=>clearTimeout(timer.current);return <div className={`message-row ${m.role}`} onPointerDown={start} onPointerUp={cancel} onPointerCancel={cancel} onContextMenu={e=>{e.preventDefault();onMenu()}}>{m.role==='user'?<div className="user-wrap"><div className="user-bubble"><RichText text={m.text} highlight={highlight}/>{(m.attachments||[]).map(a=>a.type.startsWith('image/')?<img key={a.id} className="msg-image" src={a.data} onClick={()=>onImage(a)}/>:<div key={a.id} className="file-card"><Icon name="file"/><span>{a.name}</span></div>)}</div></div>:<div className="assistant-wrap">{m.error?<div className="error-card"><div>{m.error}</div><button className="retry-clean" onClick={onRetry}>دوباره تلاش کن</button></div>:<><RichText text={m.text} highlight={highlight}/>{m.web&&<div className="web-badge"><Icon name="globe" size={14}/> Web</div>}<div className="msg-actions"><button onClick={copyMsg} className={copied?'copied':''}><Icon name={copied?'check':'copy'} size={17}/></button><button onClick={onSpeak}><Icon name="volume" size={18}/></button><button onClick={()=>notify('👍')}>♡</button><button onClick={onMenu}><Icon name="more" size={18}/></button></div></>}</div>}</div>}
function Wave({level=.1}){return <div className="wave">{Array.from({length:28},(_,i)=><i key={i} style={{height:`${6+Math.max(.08,level)*22*(.35+Math.abs(Math.sin(i*1.7))*.65)}px`}}/>)}</div>}
function AttachmentSheet({camera,photos,files,plugin,think,isFa,webSearch}){return <div className="attach-sheet"><SheetRow icon="camera" text={isFa?'دوربین':'Camera'} onClick={camera}/><SheetRow icon="image" text={isFa?'عکس‌ها':'Photos'} onClick={photos}/><SheetRow icon="file" text={isFa?'فایل‌ها':'Files'} onClick={files}/><SheetRow icon="puzzle" text={isFa?'افزونه‌ها':'Plugins'} onClick={plugin} badge={webSearch?'Web ✓':''}/><SheetRow icon="spark" text={isFa?'بیشتر فکر کن':'Think harder'} onClick={think}/></div>}
function SheetRow({icon,text,onClick,badge}){return <button className="sheet-row" onClick={onClick}><span className="sheet-icon"><Icon name={icon} size={18}/></span><span>{text}</span>{badge&&<em>{badge}</em>}</button>}
function Menu({icon,text,onClick,danger}){return <button className={`menu-item ${danger?'danger':''}`} onClick={onClick}><Icon name={icon} size={18}/><span>{text}</span></button>}
function MessageContext({msg,close,copy,select,edit,share,branch,retry,web,isFa}){return <><div className="menu-dismiss" onClick={close}/><div className="popup message-context"><div className="menu-time">{formatTime(msg.createdAt)}</div>{msg.role==='user'?<><Menu icon="copy" text={isFa?'کپی':'Copy'} onClick={copy}/><Menu icon="select" text={isFa?'انتخاب متن':'Select text'} onClick={select}/><Menu icon="edit" text={isFa?'ویرایش پیام':'Edit message'} onClick={edit}/><Menu icon="share" text={isFa?'اشتراک پرامپت':'Share prompt'} onClick={share}/></>:<><Menu icon="branch" text={isFa?'شاخه در گفتگوی جدید':'Branch in new chat'} onClick={branch}/><Menu icon="refresh" text={isFa?'تلاش دوباره':'Retry'} onClick={retry}/><Menu icon="globe" text={isFa?'جستجو در وب':'Search the web'} onClick={web}/><Menu icon="copy" text={isFa?'کپی':'Copy'} onClick={copy}/></>}</div></>}

function Drawer({state,active,selectChat,newChat,go,isFa,setChatMenu}){const [searching,setSearching]=useState(false);const [q,setQ]=useState('');const all=state.conversations.filter(c=>!c.archived).sort((a,b)=>(b.pinned-a.pinned)||(b.updatedAt-a.updatedAt));const chats=all.filter(c=>!q.trim()||c.title.toLowerCase().includes(q.trim().toLowerCase())||(c.messages||[]).some(m=>(m.text||'').toLowerCase().includes(q.trim().toLowerCase())));const nav=[['image',isFa?'تصاویر':'Images','images'],['folder',isFa?'کتابخانه':'Library','library'],['folder',isFa?'پروژه‌ها':'Projects','projects'],['clock',isFa?'زمان‌بندی':'Scheduled','scheduled'],['puzzle',isFa?'افزونه‌ها':'Plugins','plugins']];const timers={};return <aside className="drawer"><div className="drawer-head">{searching?<div className="drawer-search"><Icon name="search" size={18}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder={isFa?'جستجو در گفتگوها':'Search chats'}/><IBtn name="x" size={17} onClick={()=>{setSearching(false);setQ('')}}/></div>:<><b>MindGPT</b><IBtn name="search" onClick={()=>setSearching(true)}/></>}</div><div className="drawer-nav">{nav.map(([i,t,s])=><button key={s} onClick={()=>go(s)}><Icon name={i} size={19}/><span>{t}</span></button>)}</div><div className="drawer-sep"/><div className="chat-list">{chats.map(c=><button key={c.id} className={`chat-row ${c.id===active?.id?'active':''}`} onClick={()=>selectChat(c.id)} onPointerDown={()=>{timers[c.id]=setTimeout(()=>setChatMenu(c.id),500)}} onPointerUp={()=>clearTimeout(timers[c.id])} onPointerCancel={()=>clearTimeout(timers[c.id])} onContextMenu={e=>{e.preventDefault();setChatMenu(c.id)}}><span>{c.title}</span>{c.pinned&&<Icon name="pin" size={14}/>}<i onClick={e=>{e.stopPropagation();setChatMenu(c.id)}}>•••</i></button>)}{searching&&!chats.length&&<div className="drawer-no-results">{isFa?'نتیجه‌ای پیدا نشد':'No chats found'}</div>}</div><div className="drawer-foot"><button className="chat-new" onClick={newChat}><Icon name="edit" size={17}/>{isFa?'گفتگو':'Chat'}</button><button className="settings-btn" onClick={()=>go('settings')}><Icon name="settings" size={19}/></button></div></aside>}

function ChatContext({chat,close,patchChat,removeChat,state,setState,notify,isFa}){const [renaming,setRenaming]=useState(false);const [name,setName]=useState(chat?.title||'');if(!chat)return null;return <><div className="menu-dismiss" onClick={close}/><div className="popup chat-context">{renaming?<div className="rename-box"><input autoFocus value={name} onChange={e=>setName(e.target.value)}/><button onClick={()=>{patchChat(chat.id,c=>({...c,title:name.trim()||c.title}));close()}}><Icon name="check"/></button></div>:<><Menu icon="pin" text={chat.pinned?(isFa?'برداشتن سنجاق':'Unpin'):(isFa?'سنجاق':'Pin')} onClick={()=>{patchChat(chat.id,c=>({...c,pinned:!c.pinned}));close()}}/><Menu icon="rename" text={isFa?'تغییر نام':'Rename'} onClick={()=>setRenaming(true)}/><Menu icon="folder" text={isFa?'افزودن به پروژه':'Add to project'} onClick={()=>{const p=state.projects[0];if(p){patchChat(chat.id,c=>({...c,projectId:p.id}));notify(isFa?'به پروژه اضافه شد':'Added to project')}else notify(isFa?'اول یک پروژه بساز':'Create a project first');close()}}/><Menu icon="archive" text={isFa?'بایگانی':'Archive'} onClick={()=>{patchChat(chat.id,c=>({...c,archived:true}));close()}}/><Menu icon="trash" danger text={isFa?'حذف':'Delete'} onClick={()=>removeChat(chat.id)}/></>}</div></>}

function PlusPage({close,isFa}){
 const openTelegram=()=>{window.location.href='https://t.me/Dev_vexel'};
 const benefits=isFa?[
  ['spark','دسترسی به تجربه پیشرفته‌تر','قابلیت‌های حرفه‌ای MindGPT و امکانات جدید در یک تجربه یکپارچه.'],
  ['headphones','تجربه صوتی بهتر','گفتگوی صوتی روان‌تر و دسترسی سریع‌تر به ابزارهای صوتی.'],
  ['image','ابزارهای بیشتر','کار با تصویر، فایل، جستجوی وب و قابلیت‌های تکمیلی در یک محیط.'],
  ['clock','دسترسی و پشتیبانی بهتر','دریافت قابلیت‌های جدید و راهنمایی برای استفاده از امکانات Plus.']
 ]:[
  ['spark','More capable experience','Advanced MindGPT features and new tools in one polished experience.'],
  ['headphones','Better voice experience','Smoother voice conversations and faster access to voice tools.'],
  ['image','More tools','Work with images, files, web search and additional capabilities.'],
  ['clock','Updates & support','Get new Plus capabilities and help using advanced features.']
 ];
 return <div className="plus-page">
  <header className="plus-top"><button className="plus-close" onClick={close}><Icon name="x" size={20}/></button><span/></header>
  <main className="plus-scroll">
   <section className="plus-hero"><div className="plus-orb"><Icon name="spark" size={30}/></div><div className="plus-brand">MindGPT <span>Plus</span></div><h1>{isFa?'بیشتر از MindGPT استفاده کن':'Get more out of MindGPT'}</h1><p>{isFa?'دسترسی به تجربه‌ای کامل‌تر، سریع‌تر و حرفه‌ای‌تر برای کارهای روزمره و پیشرفته.':'Unlock a more complete, polished experience for everyday and advanced work.'}</p></section>
   <section className="plus-benefits">{benefits.map(([icon,title,desc])=><div className="plus-benefit" key={title}><div className="plus-benefit-icon"><Icon name={icon} size={22}/></div><div><b>{title}</b><p>{desc}</p></div></div>)}</section>
   <section className="plus-buy-card"><div className="plus-buy-spark">✦</div><h2>{isFa?'MindGPT Plus را می‌خواهی؟':'Want MindGPT Plus?'}</h2><p>{isFa?'برای تهیه و فعال‌سازی Plus در تلگرام به @Dev_vexel پیام بده.':'For Plus access and activation, message @Dev_vexel on Telegram.'}</p><button className="plus-telegram" onClick={openTelegram}><span>{isFa?'پیام در تلگرام':'Message on Telegram'}</span><b>@Dev_vexel</b></button></section>
   <p className="plus-footnote">{isFa?'MindGPT یک کلاینت مستقل هوش مصنوعی است.':'MindGPT is an independent AI client.'}</p>
  </main>
 </div>
}

function Page({title,back,children,right}){return <div className="screen page"><header className="page-top"><IBtn name="back" onClick={back}/><b>{title}</b><div>{right}</div></header>{children}</div>}
function Setting({icon,title,sub,onClick}){return <button className="setting" onClick={onClick}><Icon name={icon} size={20}/><span><b>{title}</b><small>{sub}</small></span><span className="setting-arrow">‹</span></button>}
function Appearance({settings,patchSettings,go,isFa}){const colors=[['blue','Blue'],['white','White'],['green','Green'],['yellow','Yellow'],['pink','Pink'],['orange','Orange'],['purple','Purple']];return <Page title={isFa?'ظاهر':'Appearance'} back={()=>go('settings')}><div className="settings-page"><div className="settings-group"><Choice title={isFa?'تیره':'Dark'} active={settings.theme==='dark'} onClick={()=>patchSettings({theme:'dark'})}/><Choice title={isFa?'روشن':'Light'} active={settings.theme==='light'} onClick={()=>patchSettings({theme:'light'})}/></div><div className="settings-group accent-group"><div className="accent-title"><Icon name="palette"/><span>{isFa?'رنگ تأکیدی':'Accent color'}</span></div>{colors.map(([id,label])=><button className="accent-choice" key={id} onClick={()=>patchSettings({accent:id})}><i className={`accent-dot ${id}`}/><b>{label}</b>{(settings.accent||'white')===id&&<Icon name="check"/>}</button>)}</div></div></Page>}
function Settings({state,patchSettings,go,isFa}){return <Page title={isFa?'تنظیمات':'Settings'} back={()=>go('chat')}><div className="settings-page"><div className="account-row"><div className="avatar">M</div><div><b>MindGPT</b><small>{isFa?'کلاینت هوش مصنوعی شخصی':'Personal AI client'}</small></div></div><div className="settings-group"><Setting icon="spark" title={isFa?'مدل':'Model'} sub={state.settings.selectedModel||FALLBACK_MODEL} onClick={()=>go('models')}/><Setting icon="user" title={isFa?'شخصی‌سازی':'Personalization'} sub={isFa?'دستورها و رفتار دستیار':'Instructions & assistant behavior'} onClick={()=>go('personalization')}/><Setting icon="mic" title={isFa?'صدا':'Voice'} sub={state.settings.voiceLanguage} onClick={()=>go('voiceSettings')}/><Setting icon="shield" title={isFa?'کنترل داده‌ها':'Data controls'} sub={isFa?'تاریخچه و حریم خصوصی':'History & privacy'} onClick={()=>go('data')}/><Setting icon="palette" title={isFa?'ظاهر':'Appearance'} sub={state.settings.theme} onClick={()=>go('appearance')}/><Setting icon="globe" title={isFa?'زبان':'Language'} sub={isFa?'فارسی':'English'} onClick={()=>patchSettings({language:isFa?'en':'fa'})}/></div><div className="settings-group"><Setting icon="download" title={isFa?'بررسی بروزرسانی':'Check for updates'} sub={isFa?'دریافت نسخه جدید داخل برنامه':'Update inside the app'} onClick={()=>native()?.checkForUpdate?.(true)}/><Setting icon="info" title={isFa?'درباره MindGPT':'About MindGPT'} sub="Version 5.5.3"/><Setting icon="settings" title={isFa?'مجوزهای برنامه':'App permissions'} sub={isFa?'میکروفون، دوربین و فایل‌ها':'Microphone, camera & files'} onClick={()=>native()?.openAppSettings?.()}/></div></div></Page>}

function ModelSettings({settings,patchSettings,apiKey,go,isFa,notify}){const [busy,setBusy]=useState(true);const [models,setModels]=useState(settings.models||[]);const [info,setInfo]=useState(settings.modelInfo||{});async function refresh(){setBusy(true);try{const r=await loadModels(settings,apiKey);setModels(r.models);setInfo(r.info);const chosen=r.models.includes(settings.selectedModel)?settings.selectedModel:(r.models[0]||settings.selectedModel);patchSettings({provider:'CODECRAFT',baseUrl:CODECRAFT_BASE,models:r.models,modelInfo:r.info,selectedModel:chosen});}catch(e){notify(e.message||'Model error')}finally{setBusy(false)}}useEffect(()=>{refresh()},[]);return <Page title={isFa?'مدل‌ها':'Models'} back={()=>go('settings')}><div className="model-page"><div className="model-head"><div><b>{isFa?'مدل فعال':'Active model'}</b><small>{settings.selectedModel||FALLBACK_MODEL}</small></div><button onClick={refresh} disabled={busy}><Icon name="refresh" size={18}/>{busy?(isFa?'در حال دریافت…':'Loading…'):(isFa?'بروزرسانی':'Refresh')}</button></div>{models.map(id=>{const m=info[id]||{};const caps=m.capabilities||[];return <button key={id} className={`model-card ${settings.selectedModel===id?'selected':''}`} onClick={()=>patchSettings({selectedModel:id})}><div className="model-radio">{settings.selectedModel===id&&<i/>}</div><div className="model-copy"><b>{m.name||id}</b><code>{id}</code>{m.description&&<p>{m.description}</p>}<div className="cap-row">{caps.map(c=><span key={c}>{c}</span>)}</div>{m.context_window&&<small>{isFa?'کانتکست':'Context'}: {Number(m.context_window).toLocaleString()}</small>}</div></button>})}{!busy&&!models.length&&<EmptyHub text={isFa?'مدلی در دسترس نیست':'No models available'}/>}</div></Page>}

function Personalization({settings,patchSettings,go,isFa}){return <Page title={isFa?'شخصی‌سازی':'Personalization'} back={()=>go('settings')}><div className="form-page"><div className="form-card"><label>{isFa?'دستورهای شخصی':'Custom instructions'}</label><textarea className="big-area" value={settings.systemPrompt||''} onChange={e=>patchSettings({systemPrompt:e.target.value})}/></div><div className="form-card"><Toggle title={isFa?'ارسال با Enter':'Send with Enter'} value={settings.sendOnEnter} onChange={v=>patchSettings({sendOnEnter:v})}/></div></div></Page>}
function VoiceSettings({settings,patchSettings,go,isFa}){return <Page title={isFa?'صدا':'Voice'} back={()=>go('settings')}><div className="settings-page"><div className="settings-group"><Choice title="فارسی (ایران)" active={settings.voiceLanguage==='fa-IR'} onClick={()=>patchSettings({voiceLanguage:'fa-IR'})}/><Choice title="English (US)" active={settings.voiceLanguage==='en-US'} onClick={()=>patchSettings({voiceLanguage:'en-US'})}/><Toggle title={isFa?'خواندن خودکار پاسخ‌ها':'Read replies aloud'} value={settings.autoRead} onChange={v=>patchSettings({autoRead:v})}/></div><p className="page-note">{isFa?'تشخیص صدا داخل خود برنامه انجام می‌شود و پنجره میکروفون Google باز نمی‌شود.':'Speech recognition stays inside the app; the Google microphone screen is not opened.'}</p></div></Page>}
function DataControls({state,setState,go,isFa,notify}){return <Page title={isFa?'کنترل داده‌ها':'Data controls'} back={()=>go('settings')}><div className="settings-page"><div className="settings-group"><Setting icon="archive" title={isFa?'گفتگوهای بایگانی‌شده':'Archived chats'} sub={`${state.conversations.filter(c=>c.archived).length}`} onClick={()=>notify(isFa?'از Library قابل مشاهده است':'Available from Library')}/><Setting icon="download" title={isFa?'خروجی گرفتن از داده‌ها':'Export data'} sub={isFa?'اشتراک فایل JSON':'Share JSON'} onClick={()=>shareText(JSON.stringify(state,null,2))}/><Setting icon="trash" title={isFa?'پاک کردن همه گفتگوها':'Clear all chats'} sub={isFa?'این کار برگشت‌پذیر نیست':'This cannot be undone'} onClick={()=>{const d=defaultState();setState(s=>({...s,conversations:d.conversations,activeId:d.conversations[0].id}));notify(isFa?'گفتگوها پاک شدند':'Chats cleared')}}/></div></div></Page>}
function Choice({title,active,onClick}){return <button className="choice" onClick={onClick}><span>{title}</span>{active&&<Icon name="check"/>}</button>}
function Toggle({title,value,onChange}){return <div className="toggle-row"><span>{title}</span><button className={`switch ${value?'on':''}`} onClick={()=>onChange(!value)}><i/></button></div>}

function HubScreen({kind,state,setState,go,isFa,selectChat,setImageView,notify}){const titles={images:isFa?'تصاویر':'Images',library:isFa?'کتابخانه':'Library',projects:isFa?'پروژه‌ها':'Projects',scheduled:isFa?'زمان‌بندی':'Scheduled',plugins:isFa?'افزونه‌ها':'Plugins'};const attachments=state.conversations.flatMap(c=>c.messages.flatMap(m=>(m.attachments||[]).map(a=>({...a,chatId:c.id,chatTitle:c.title}))));if(kind==='images')return <Page title={titles[kind]} back={()=>go('chat')}><div className="image-grid">{attachments.filter(a=>a.type.startsWith('image/')).map(a=><button key={a.id} onClick={()=>setImageView(a)}><img src={a.data}/></button>)}{!attachments.some(a=>a.type.startsWith('image/'))&&<EmptyHub text={isFa?'هنوز تصویری نداری':'No images yet'}/>}</div></Page>;
 if(kind==='library')return <Page title={titles[kind]} back={()=>go('chat')}><div className="hub-list">{state.conversations.filter(c=>c.archived).map(c=><button key={c.id} onClick={()=>selectChat(c.id)}><Icon name="archive"/><span><b>{c.title}</b><small>{isFa?'بایگانی‌شده':'Archived'}</small></span></button>)}{attachments.map(a=><button key={a.id} onClick={()=>selectChat(a.chatId)}><Icon name={a.type.startsWith('image/')?'image':'file'}/><span><b>{a.name}</b><small>{a.chatTitle}</small></span></button>)}{!attachments.length&&!state.conversations.some(c=>c.archived)&&<EmptyHub text={isFa?'کتابخانه خالی است':'Library is empty'}/>}</div></Page>;
 if(kind==='projects')return <Projects state={state} setState={setState} back={()=>go('chat')} isFa={isFa} selectChat={selectChat}/>;
 if(kind==='scheduled')return <Scheduled state={state} setState={setState} back={()=>go('chat')} isFa={isFa}/>;
 return <Page title={titles[kind]} back={()=>go('chat')}><div className="settings-page"><div className="plugin-card"><div><Icon name="globe"/><b>{isFa?'جستجوی وب':'Web Search'}</b></div><p>{isFa?'برای پیام‌های پشتیبانی‌شده از جستجوی وب ارائه‌دهنده استفاده می‌کند.':'Uses the provider web-search tool for supported models.'}</p><span className="plugin-on">{isFa?'فعال':'Enabled'}</span></div><div className="plugin-card"><div><Icon name="file"/><b>{isFa?'فایل و تصویر':'Files & Images'}</b></div><p>{isFa?'تصاویر را همراه درخواست به مدل‌های چندرسانه‌ای می‌فرستد.':'Sends images to multimodal models with your prompt.'}</p><span className="plugin-on">{isFa?'فعال':'Enabled'}</span></div></div></Page>}
function EmptyHub({text}){return <div className="empty-hub"><Icon name="spark" size={30}/><span>{text}</span></div>}
function Projects({state,setState,back,isFa,selectChat}){const [name,setName]=useState('');function add(){if(!name.trim())return;setState(s=>({...s,projects:[...s.projects,{id:uid(),name:name.trim(),createdAt:now()}]}));setName('')}return <Page title={isFa?'پروژه‌ها':'Projects'} back={back}><div className="hub-create"><input value={name} onChange={e=>setName(e.target.value)} placeholder={isFa?'نام پروژه':'Project name'}/><button onClick={add}><Icon name="plus"/></button></div><div className="project-list">{state.projects.map(p=><div className="project" key={p.id}><div className="project-head"><Icon name="folder"/><b>{p.name}</b></div>{state.conversations.filter(c=>c.projectId===p.id).map(c=><button key={c.id} onClick={()=>selectChat(c.id)}>{c.title}</button>)}</div>)}</div></Page>}
function Scheduled({state,setState,back,isFa}){const [text,setText]=useState('');const [when,setWhen]=useState('');function add(){if(!text.trim()||!when)return;setState(s=>({...s,schedules:[...s.schedules,{id:uid(),text:text.trim(),when,done:false}]}));setText('');setWhen('')}return <Page title={isFa?'زمان‌بندی':'Scheduled'} back={back}><div className="schedule-form"><input value={text} onChange={e=>setText(e.target.value)} placeholder={isFa?'یادداشت یا پرامپت':'Note or prompt'}/><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/><button className="primary" onClick={add}>{isFa?'افزودن':'Add'}</button></div><div className="schedule-list">{state.schedules.map(x=><div key={x.id}><Icon name="clock"/><span><b>{x.text}</b><small>{x.when.replace('T',' ')}</small></span><button onClick={()=>setState(s=>({...s,schedules:s.schedules.filter(z=>z.id!==x.id)}))}>×</button></div>)}</div></Page>}

function EditMessage({msg,close,save}){const [text,setText]=useState(msg.text||'');return <div className="overlay-page"><header className="page-top"><IBtn name="x" onClick={close}/><b>Edit message</b><span/></header><div className="edit-note">Editing this message will restart the conversation from here.</div><textarea className="edit-message" autoFocus value={text} onChange={e=>setText(e.target.value)}/><div className="edit-actions"><button className="primary" onClick={()=>save(text)}>Save</button></div></div>}
function SelectText({msg,close}){return <div className="overlay-page"><header className="page-top"><IBtn name="back" onClick={close}/><b>Select text</b><span/></header><div className="select-text" dir="auto">{msg.text}</div></div>}
function TtsBar({item,close,isFa}){const [playing,setPlaying]=useState(true);useEffect(()=>{window.__ttsState=s=>{if(s==='done'||s==='stopped'||s==='error')setPlaying(false)};return()=>delete window.__ttsState},[]);return <div className="tts-bar"><button onClick={close}><Icon name="x" size={18}/></button><div className="tts-wave"><i/><i/><i/><i/><i/><i/><i/></div><div className="tts-title">{item.title}</div><button onClick={()=>{if(playing){native()?.stopSpeak?.();setPlaying(false)}else{native()?.speak?.(item.text,isFa?'fa-IR':'en-US');setPlaying(true)}}}><Icon name={playing?'pause':'play'} size={18}/></button></div>}
function VoiceMode({isFa,settings,close,onText,notify}){const [state,setState]=useState('connecting');const [level,setLevel]=useState(.05);const [partial,setPartial]=useState('');const [muted,setMuted]=useState(false);useEffect(()=>{const prev={state:window.__speechState,level:window.__speechLevel,partial:window.__speechPartial,result:window.__speechResult,error:window.__speechError};window.__speechState=s=>setState(s);window.__speechLevel=v=>setLevel(v);window.__speechPartial=t=>setPartial(t);window.__speechResult=t=>{onText(t);setPartial('');setState('listening')};window.__speechError=()=>{setState('error');notify(isFa?'تشخیص صدا در دسترس نیست':'Speech recognition unavailable')};native()?.startSpeech?.(settings.voiceLanguage|| (isFa?'fa-IR':'en-US'));return()=>{native()?.stopSpeech?.();window.__speechState=prev.state;window.__speechLevel=prev.level;window.__speechPartial=prev.partial;window.__speechResult=prev.result;window.__speechError=prev.error}},[]);function mute(){if(muted){native()?.startSpeech?.(settings.voiceLanguage||'fa-IR');setMuted(false)}else{native()?.stopSpeech?.();setMuted(true)}}return <div className="voice-screen"><div className="voice-top"><IBtn name="sliders" className="round-dark"/><IBtn name="menu" className="round-dark"/></div><div className="voice-center"><div className={`voice-orb ${state}`} style={{'--level':level}}><div className="orb-glow"/></div><div className="voice-caption">{partial|| (state==='processing'?(isFa?'در حال پردازش…':'Processing…'):state==='error'?(isFa?'اتصال صدا برقرار نشد':'Voice unavailable'):(isFa?'در حال گوش دادن…':'Listening…'))}</div></div><div className="voice-controls"><button className="voice-close" onClick={close}><Icon name="x"/></button><button className={`voice-mute ${muted?'muted':''}`} onClick={mute}><Icon name="mic"/></button><div className="voice-pill">{isFa?'از MindGPT بپرس':'Ask MindGPT'} <span>＋</span></div></div></div>}
function UpdatePrompt({info,close,isFa}){const [progress,setProgress]=useState(null);const [status,setStatus]=useState('ready');useEffect(()=>{const prevP=window.__updateProgress,prevS=window.__updateStatus;window.__updateProgress=p=>{setProgress(Math.max(0,Math.min(100,Number(p)||0)));setStatus(Number(p)>=100?'readyToInstall':'downloading')};window.__updateStatus=s=>{setStatus(s);if(['readyToInstall','installing','permission'].includes(s))setProgress(100)};return()=>{window.__updateProgress=prevP;window.__updateStatus=prevS}},[]);function start(){if(['readyToInstall','installing','permission'].includes(status)){native()?.installDownloadedUpdateNow?.();return}setProgress(0);setStatus('downloading');native()?.downloadAndInstall?.(info.apkUrl||info.url)}return <><div className="sheet-back update-back" onClick={status==='downloading'?undefined:close}/><div className="update-card"><div className="update-icon"><Icon name="download" size={25}/></div><h3>{isFa?'نسخه جدید MindGPT آماده است':'A new MindGPT update is ready'}</h3><p>{info.name||info.versionName||''}</p>{progress!==null&&<div className="update-progress"><div className="update-progress-track"><i style={{width:`${progress}%`}}/></div><b>{Math.round(progress)}%</b><small>{progress>=100?(isFa?'آماده نصب':'Ready to install'):(isFa?'در حال دانلود داخل برنامه…':'Downloading in app…')}</small></div>}<button className="primary" disabled={status==='downloading'} onClick={start}>{status==='downloading'?(isFa?'در حال دانلود…':'Downloading…'):(progress>=100?(isFa?'نصب بروزرسانی':'Install update'):(isFa?'دانلود و بروزرسانی':'Download & update'))}</button><button className="update-later" disabled={status==='downloading'} onClick={close}>{isFa?'بعداً':'Later'}</button></div></>}

function ImageViewer({item,close,remove}){return <div className="image-viewer"><header><IBtn name="x" onClick={close}/><div><IBtn name="more"/><IBtn name="download"/><button className="share-pill" onClick={()=>shareText(item.data)}>Share</button></div></header><div className="image-stage"><img src={item.data}/></div><footer><button><Icon name="edit"/><span>Edit</span></button><button><Icon name="image"/><span>Resize</span></button><button onClick={remove}><Icon name="trash"/><span>Remove</span></button></footer></div>}

createRoot(document.getElementById('root')).render(<App/>);
